//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContainermanagementsystemTP034963.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargo
    {
        public int Id { get; set; }
        public Nullable<double> volume { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<int> customerid { get; set; }
        public Nullable<int> warehouseid { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
